appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KDTwWahLld9REtPhwxG3eC794zl3XLHEeC9kD4oBBJ+pV6FV9G08oYq1vi3VNQq5AkqXVi4/kNDV4GQowYm/PpfET9nh1nvy6wAQsok5T/KKNMF6lAO1vzPpTlzGKS0jD0WvysIfsw4DfQbg1qMGEJoYrF5KfhkxFFmnRZcYmN3CevhzXNoqxTCrwHWTEhUbqh2g4heR2xnFbPZsGBfz7Xjn1rf3f/bthP1pojEA7f9AcV7xZpn8RVPek2JGQAMbGcPE8LRe6zSMT5b5ZvmT7M7dIgcfrG2Ng3Iuz9xdpY9XIyGLue4re0HNEdm7TJAPcjRUCLIpH+e2kQRfVvLoe4kBOsNWJ9AAZljwosENwPTDtluTIPSa4c+hdbxQSbrVChwhItFpnIROP4yHYEagHWBQayRNzZhuUKhhs4CQql6p2uUGjXHy33WyXXYuGEiFeI963rtL2pmoAaPTiOvCMnFjTu1+mwpQ479am7T99vtdVt4xw+z5QNWZb0UQjnkxkcCW0JI73fRMEBY6/D1+ETazdbXjsNlsU9OC7/sp5zvNlT9i24tF80741IAUPUD77tcYRLsj9q11IYv5runUZAM/7f0WZZU2xme5Mk6dEqFtPen1P53QnrpPu5mkhEj2fEUDyAFFyAHuiD3Nvu7MFfJxLLEYxSHqUGVAZgFwoS4=}
