travis:
  secure:
    BINSTAR_TOKEN: Prv3kY/5PUApjAmg/Xulk0FY57BovnCN8XYOgHZCHVDpjKjUcFZQmlOSj5f0CzkJLO559OFVpZQZemADll5De3HKT3MQnSBkMRwGaWrwrxechjwOerlc6PFEvUE/rOnbCf0qLCuKaDVDG/a8MjSq2/4B41bjNlRrn8IDD1F4OvjNRA0JA5RrtFU3fhkcvJQE11GXAQTEZZ9DJb9z5zmQz6EgnZ5Nmejdn90NEFDkBMdRe51aWT9WUYhtECES9LgKTwURYp2PTwUDLpvw1PmvLUtda5No1CRkijpnba11rIReByvxXDBC5v1MuwoPFUkfbMMHb2gnAQQ+dhwrh/e4Oxm2GONK6rotKU+hGqk/PzJ8pLA7sR2NZRbwTD8EtAb2ItMDgojwNN8dmB9xb4Snkyuj3EA2nqEL39Ld80DE3yaG1SPQFyCtcewIOsghCPlGep/EmUylgXHegyTh3L/YrQ0hGiNPoMLMQNtknKSm02g4p8khWwzdrQPM51TfS8fLEbf1XMZFMU+lO5yHEGzem8l0nSryOwXtn8n73D7obIIj6A3Xr0md5cxCSpgMvVbrluEMC+HD/GUyNhsHjBVxoQvEEnRA8KnUxztJpqAL7vyPSOMIYp+0kXk5AtJbiHSxv1fp7rIcilHX4rXuaTX1q9QaTapY4289teaaGf5G/SM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
